### PR TITLE
solve sqlalchemy multiplte relationships issue

### PR DESCRIPTION
**Pull request by jubafourali**
This PR is to solve the issue https://github.com/flask-admin/flask-admin/issues/1740

### CODE REVIEW

**Comment by petrus-jvrensburg** [comment]
Thanks for this @jubafourali, but please first open an issue, and use it to describe the problem that you're solving here.

**Comment by jubafourali** [comment]
> Thanks for this @jubafourali, but please first open an issue, and use it to describe the problem that you're solving here.

**Comment by jubafourali** [comment]
> Thanks for this @jubafourali, but please first open an issue, and use it to describe the problem that you're solving here.

Thank you @petrus-jvrensburg for your notice, issue tagged above

**Comment by vinayak-kaniyarakkal** [comment]
Can we merge this PR?

**Comment by jubafourali** [comment]
> Can we merge this PR?

This can be done only by people with write access

**Comment by vinayak-kaniyarakkal** [comment]
@pawl @alanhamlett @mrjoes Could you please merge this?

**Review by alanhamlett — APPROVED** [review]

**Pull request merged**
