### PR TITLE
Bootswatch 5.2.3

### PR DESCRIPTION
**Pull request by mariofix**
Issue #2350 

* bootswatch/bootstrap 5.2.3 upgrade
* bootstrap-icons support
* jquery3.7.0

### CODE REVIEW

**Comment by Ayfri** [comment]
Any update ?

**Comment by macnewbold** [comment]
This week makes 6 months that this PR has been here waiting. Any chance it can get reviewed and merged into an upcoming release sometime soon?

**Comment by hasansezertasan** [comment]
Well it's quite sad to see this waiting and maybe getting outdated...

**Comment by hasansezertasan** [comment]
@mariofix, I think you can turn this PR into a package. I think that would be great! 🚀

**Comment by mariofix** [comment]
Since there are no updates for the review, PR closed.

**Comment by hasansezertasan** [comment]
> Since there are no updates for the review, PR closed.

Hey @mariofix, the project is alive again and there is another PR (#2432) related to this. Please check out if you are still interested in 🙏.

**Pull request closed without merging**
