### PR TITLE
prefix blueprint name with admin to prevent conflicts... 

### PR DESCRIPTION
**Pull request by alanhamlett**
...with user-defined blueprint names

### CODE REVIEW

**Comment by jmagnusson** [comment]
This is a must have imo. It could easily happen otherwise that the generated names collide with an existing blueprint otherwise.

**Comment by deniszgonjanin** [comment]
:+1: would be nice to have this.

**Comment by jmagnusson** [comment]
@alanhamlett Could you update your PR to reflect the latest code?
@mrjoes? Would it be possible to get this merged in? It's quite easy to get name conflicts with your own blueprints.

**Comment by mrjoes** [comment]
I'd say this pull request is no longer necessary. Now it is possible to override automatic names in `BaseView`: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/base.py#L209

For example:
```python
class MyBaseView(BaseView):
    def _get_endpoint(self, endpoint):
        if endpoint:
            return endpoint

        return 'admin.%s' % self.__class__.__name__.lower()
```

**Comment by jmagnusson** [comment]
Thanks @mrjoes. Doesn't it make sense to be able to namespace them either way though?

**Comment by mrjoes** [comment]
Yeah, but it'll break backwards compatibility for everyone who uses `url_for('myadminview.index')`

**Comment by jmagnusson** [comment]
Figures... :smile: Perhaps one could optionally supply a blueprint prefix to `init_app`?

```python
admin = Admin()
...
admin.init_app(myapp, blueprint_prefix='myadmin')
```

**Comment by mrjoes** [comment]
Yeah, but one would have to define their own classes anyway (security, maybe global customizations, etc). So that's better place to have this logic in.

**Comment by alanhamlett** [comment]
So this pull request isn't needed now?

**Comment by jmagnusson** [comment]
@mrjoes with your example all the URLs will be changed as well. I just want to change the name of the resource, and keep the current URL. How would I do that?

**Comment by mrjoes** [comment]
Good catch, automatically generated URLs use endpoint name.

I'll move URL scaffolding logic to a separate, overridable, method later today.

**Comment by jmagnusson** [comment]
Great! :+1:

**Pull request closed without merging**
