### PR TITLE
Bootstrap4 Work-In-Progress

### PR DESCRIPTION
**Pull request by petrus-jvrensburg**
closes #1674
@waylonwang, @Insutanto, @ryanbeymer, @Fomys 
Help here would be appreciated.

### CODE REVIEW

**Comment by rsnyman** [comment]
So, the modals still don't work. I don't use them, so it doesn't directly affect me, but I found out that if the templates just use the bundled Bootstrap JS file, then they work. What's the best way of getting a fix into this branch?

**Comment by Insutanto** [comment]
I have a new pull request to boostrap4 branch to support column_editable_list in bootstrap4's template mode.

**Comment by Insutanto** [comment]
> So, the modals still don't work. I don't use them, so it doesn't directly affect me, but I found out that if the templates just use the bundled Bootstrap JS file, then they work. What's the best way of getting a fix into this branch?

but, it is work in my test case

**Comment by Insutanto** [comment]
#1903 I have a new pull request to boostrap4 branch to support column_editable_list in bootstrap4's template mode.:smile:

**Comment by rsnyman** [comment]
I just tried this branch again. One issue I'm running into is that the drop down menu items in the navbar menu are all white on a white background. I think this is due to the wrong markup in the template.

**Comment by michaelbukachi** [comment]
> I just tried this branch again. One issue I'm running into is that the drop down menu items in the navbar menu are all white on a white background. I think this is due to the wrong markup in the template.

I'm trying to address this issue. What swatch did you use?

**Comment by michaelbukachi** [comment]
> I just tried this branch again. One issue I'm running into is that the drop down menu items in the navbar menu are all white on a white background. I think this is due to the wrong markup in the template.

Hey. I looked into this.
Changing `bootstrap4/layout.html`, line 48, from:
```
<a class="nav-link" href="{{ child.get_url() }}"{% if child.target %}
```
to
```
<a class="nav-link text-reset" href="{{ child.get_url() }}"{% if child.target %}
```
Also, we need to add some bottom margin to the navbar. Adding `mb-2` to `nav` seems to do the trick. How can I contribute to this PR? would love to see this merged.

**Comment by rsnyman** [comment]
@michaelbukachi Fork the repo, clone it locally, checkout the "boostrap4" branch, and once you've committed the changes, make a pull request against the bootstrap4 branch.

**Comment by TitaniumHocker** [comment]
Hey, @rsnyman!
@michaelbukachi PR seems work well for dropdown items. Can you check and merge it?
I'm planning to add some fixes for `FileAdmin` and `RedisCli` in next couple of days, maybe search field and filters can be optimized. It will be easier for me to make my changes after the merge.

**Comment by michaelbukachi** [comment]
Awesome! @TitaniumHocker Is there anything else that is pending? I've got quite a bit of time for the next couple of days.

**Comment by TitaniumHocker** [comment]
> Awesome! @TitaniumHocker Is there anything else that is pending? I've got quite a bit of time for the next couple of days.

Yes there are some additional fixes that can be done.

**First of all there is some crap with boolean field**.
It is located in the center of the form and occupies the entire row. And it's looks the same on bootstrap3. In my opinion it is a bug that looks weird.
There is a screenshot for firefox:

изображение

And here is for chrome:

изображение
On the screenshot from chrome you can see that boolean field use all row.
There is some "hack" to fix this in `ModelView` configuration:
```python
    form_widget_args = {
        'active': {
            'style': 'width: 1em; height: 1em; margin-top: .6em'
        }
    }
```
With this hack that will look like this in chrome:

изображение

But in my opinion this solution looks like "duct tape" or "Horrible piece of sh*t" in Linus Torvalds terminology.

**Another thing that can be fixed - deleting confirmation.**
On bs3 there is confirmation window for deleting objects:

изображение
_"Отмена" is Cancel on Russian._

Now, when using BS4, deletion occurs without this confirmation. It looks like a bug.

**Comment by michaelbukachi** [comment]
> > Awesome! @TitaniumHocker Is there anything else that is pending? I've got quite a bit of time for the next couple of days.
> 
> Yes there are some additional fixes that can be done.
> 
> **First of all there is some crap with boolean field**.
> It is located in the center of the form and occupies the entire row. And it's looks the same on bootstrap3. In my opinion it is a bug that looks weird.
> There is a screenshot for firefox:
> 
> изображение
> 
> And here is for chrome:
> 
> изображение
> On the screenshot from chrome you can see that boolean field use all row.
> There is some "hack" to fix this in `ModelView` configuration:
> 
> ```python
>     form_widget_args = {
>         'active': {
>             'style': 'width: 1em; height: 1em; margin-top: .6em'
>         }
>     }
> ```
> 
> With this hack that will look like this in chrome:
> 
> изображение
> 
> But in my opinion this solution looks like "duct tape" or "Horrible piece of sh*t" in Linus Torvalds terminology.
> I think there must be better way to do it.
> 
> **Another thing that can be fixed - deleting confirmation.**
> On bs3 there is confirmation window for deleting objects:
> 
> изображение
> _"Отмена" is Cancel on Russian. Don't know how to switch this to English only for browser._
> 
> Now, when using BS4, deletion occurs without this confirmation. It looks like a bug.

Cool. On it.

**Comment by TitaniumHocker** [comment]
I'm done with #2014, need review and if its ok - merge

**Comment by michaelbukachi** [comment]
Nice. Is there anything else that is pending?

**Comment by TitaniumHocker** [comment]
Yes, I found that sub category is broken.
That is screenshot with bs3:
изображение

That what I see with bs4:
изображение

And I found simple fix that need to be done. Duplicated `col-auto` class need to be removed from _/templates/bootstrap4/admin/model/list.html_, line 55:
```jinja
        {% if search_supported %}
        <li class="nav-item col-auto">
            {{ model_layout.search_form() }}
        </li>
        {% endif %}
```

In screenshots I used application from `sqla` example.

**Comment by michaelbukachi** [comment]
> ```
> {% if search_supported %}
> ```

The current implementation uses `css:hover` to show the subcategory. So this won't work on touch screens. Should we opt for a click version instead?
Also, the display of the menu is hard coded for the right side. This might cause the layout to break in a situation where there is not enough space left on the right side of the navbar.

**Comment by TitaniumHocker** [comment]
> The current implementation uses `css:hover` to show the subcategory. So this won't work on touch screens. Should we opt for a click version instead?
> Also, the display of the menu is hard coded for the right side. This might cause the layout to break in a situation where there is not enough space left on the right side of the navbar.

I think something like [this](https://www.jqueryscript.net/menu/multi-level-dropdowns-bootstrap.html) can be used with click version instead of hover. 
Here is an example of running out of space behavior, I used mobile device emulation in firefox:
изображение

It is hardcoded to use right side for subdropdowns, but I think this display is acceptable for mobile device.

**Comment by TitaniumHocker** [comment]
I'm also found that error messages in inline editing looks broken.
Here is screenshot for bs3:
изображение

And here for bs4:
изображение

**Comment by michaelbukachi** [comment]
> I'm also found that error messages in inline editing looks broken.
> Here is screenshot for bs3:
> изображение
> 
> And here for bs4:
> изображение

Interesting. Let me take a look. I've already created a PR for the previous issue.

**Comment by michaelbukachi** [comment]
> I'm also found that error messages in inline editing looks broken.
> Here is screenshot for bs3:
> изображение
> 
> And here for bs4:
> изображение

Fixed in #2015

**Comment by TitaniumHocker** [comment]
Added another fix in #2017

**Comment by TitaniumHocker** [comment]
I couldn't find any more markup issues. @mrjoes can you check this branch for merging?

**Comment by mrjoes** [comment]
Sure. I will delay new release by a week or two in case there will be additional fixes.

**Comment by Insutanto** [comment]
> Sure. I will delay new release by a week or two in case there will be additional fixes.

Maybe, It is time to release a new version? :tada:

**Comment by TitaniumHocker** [comment]
I installed master branch for one of my projects and found that date picker seems to be broken(the selects must be wider to accommodate values, and the cancel button must be red):
calendar
I was going to fix it this weekend, if someone has the time and desire to do it sooner you can do it instead of me. I think after this fix it will be possible to make a release.

**Comment by michaelbukachi** [comment]
> I installed master branch for one of my projects and found that date picker seems to be broken(the selects must be wider to accommodate values, and the cancel button must be red):
> calendar
> I was going to fix it this weekend, if someone has the time and desire to do it sooner you can do it instead of me. I think after this fix it will be possible to make a release.

I'll do a PR tonight.

**Comment by michaelbukachi** [comment]
@TitaniumHocker Do you mind providing the steps to replicate it.  This is what I get I click on a date field and datetime field.
screenshot_20200827194813
screenshot_20200827195217

**Comment by TitaniumHocker** [comment]
> @TitaniumHocker Do you mind providing the steps to replicate it. This is what I get I click on a date field and datetime field.
> screenshot_20200827194813
> screenshot_20200827195217

Seems like styles for this date(or date + time) picker is stored in `daterangepicker-bs3.css`. There must be used separate version for bs4(with optimizations for bs4).
In your case, the selectors are displayed correctly due to the fact that in your browser the default font size is set smaller than in my browser. The main problem is that the width for these selectors is set in pixels or percent, although it is better to use modern font-size based units such as `rem` or `em`. With these units, the size of the selectors will be optimal regardless of the font size used.

**Comment by michaelbukachi** [comment]
Ah. I see.

**Comment by michaelbukachi** [comment]
> > @TitaniumHocker Do you mind providing the steps to replicate it. This is what I get I click on a date field and datetime field.
> > screenshot_20200827194813
> > screenshot_20200827195217
> 
> Seems like styles for this date(or date + time) picker is stored in `daterangepicker-bs3.css`. There must be used separate version for bs4(with optimizations for bs4).
> In your case, the selectors are displayed correctly due to the fact that in your browser the default font size is set smaller than in my browser. The main problem is that the width for these selectors is set in pixels or percent, although it is better to use modern font-size based units such as `rem` or `em`. With these units, the size of the selectors will be optimal regardless of the font size used.

What browser and OS are you using? Maybe I can try replicated the environment.

**Comment by TitaniumHocker** [comment]
> What browser and OS are you using? Maybe I can try replicated the environment.

Firefox 79.0 on Manjaro GNU/Linux.
You can try simply increasing the default font size used in your browser to reproduce.

**Comment by michaelbukachi** [comment]
Do we need to add a bit of margin to the top of Navbar :thinking: ?

**Comment by Insutanto** [comment]
> Do we need to add a bit of margin to the top of Navbar 🤔 ?

What's wrong with the margin to the top of Navbar? 🤔

**Comment by michaelbukachi** [comment]
Bootstrap 3
screenshot_20200909170209

Bootstrap 4
screenshot_20200909170301

**Comment by TitaniumHocker** [comment]
It's normal for bs4 styling.
You can see examples from their official website:
https://getbootstrap.com/docs/4.5/examples/product/
https://getbootstrap.com/docs/4.5/examples/album/

**Comment by michaelbukachi** [comment]
I'm getting a sporadic error `jinja2.exceptions.UndefinedError: 'None' has no attribute`.It's caused by the delete action on the listing page.
```
Traceback (most recent call last):
  File "/Projects/PycharmProjects/oa/core/__init__.py", line 98, in __call__
    return app(environ, start_response)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/model/base.py", line 2069, in index_view
    extra_args=view_args.extra_args,
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/model/list.html", line 6, in top-level template code
    {% import 'admin/model/row_actions.html' as row_actions with context %}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/Projects/PycharmProjects/oa/extensions/flask_secure_admin/templates/secure_admin/master.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/base.html", line 39, in top-level template code
    {% block page_body %}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/base.html", line 75, in block "page_body"
    {% block body %}{% endblock %}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/model/list.html", line 68, in block "body"
    {% block model_list_table %}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/model/list.html", line 116, in block "model_list_table"
    {% block list_row scoped %}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/model/list.html", line 122, in block "list_row"
    {% block list_row_actions_column scoped %}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/model/list.html", line 125, in block "list_row_actions_column"
    {% block list_row_actions scoped %}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/model/list.html", line 127, in block "list_row_actions"
    {{ action.render_ctx(get_pk_value(row), row) }}
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/model/template.py", line 16, in render_ctx
    return self.render(context, row_id, row)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/model/template.py", line 74, in render
    return m(self, row_id, row)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/Projects/PycharmProjects/oa/venv/lib/python3.7/site-packages/flask_admin/templates/bootstrap4/admin/model/row_actions.html", line 27, in template
    {{ delete_form.id(value=get_pk_value(row)) }}
jinja2.exceptions.UndefinedError: 'None' has no attribute 'id'

```

It seems this section in `flask_admin/templates/bootstrap4/admin/model/row_actions.html`
```
<form class="icon" method="POST" action="{{ get_url('.delete_view') }}">
  {{ delete_form.id(value=get_pk_value(row)) }}
  {{ delete_form.url(value=return_url) }}
  {% if delete_form.csrf_token %}
  {{ delete_form.csrf_token }}
  {% elif csrf_token %}
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  {% endif %}
  <button onclick="return faHelpers.safeConfirm('{{ _gettext('Are you sure you want to delete this record?') }}');" title="{{ _gettext('Delete record') }}">
    <span class="fa fa-trash glyphicon glyphicon-trash"></span>
  </button>
</form>
```
is not guarded against possible `None` values.

**Comment by michaelbukachi** [comment]
Reloading the page resolves the issue but it happens again randomly.

**Comment by TitaniumHocker** [comment]
I'm using flask-admin from master branch and never saw something like this.

**Comment by michaelbukachi** [comment]
I've also been using it for weeks. The only change I can think that brought about this weird behaviour is the introduction of `Flask-Session` earlier this week into our codebase. Does `Flask-Admin` make use flask's session object :thinking: ?

**Comment by TitaniumHocker** [comment]
I think some one need to figure out with this #2022 and new version can be released.

**Comment by michaelbukachi** [comment]
> I think some one need to figure out with this #2022 and new version can be released.

Seems a fix was done but a PR wasn't made. What's the fix so that I can do a PR?

**Comment by TitaniumHocker** [comment]
Yes, this fix seems to be working fine, but I'm not really in js, so I don't know if it breaks something else.

**Comment by michaelbukachi** [comment]
> Yes, this fix seems to be working fine, but I'm not really in js, so I don't know if it breaks something else.

I'll take a look.

**Comment by TitaniumHocker** [comment]
@mrjoes Can you check the current state of the master branch and, if everything works correctly, release a new version?

**Comment by mrjoes** [comment]
Yes, will try it out this weekend.

**Pull request merged**
