### PR TITLE
On adding a text filter, set input focus to allow immediate typing

### PR DESCRIPTION
**Pull request by jnga**
Upon choosing a text filter to add, it would be useful to be able to immediately type into the text box rather than first having to click in it.

### CODE REVIEW

**Comment by jnga** [comment]
The CI build failed on submitting this pull request, but the failure appears unrelated to this pull request.

One test failed: flask_admin.tests.test_form_upload.test_image_upload_field

**Comment by pawl** [comment]
Looks like the new Pillow 3.0.0 introduced the bug. The error I get when I try to save images looks like this: "Invalid image: cannot identify image file <FileStorage: u'copyleft.tiff' ('image/tiff')>"

 One option is to set Pillow in the requirements to 2.9.0, but I'm looking into another fix.

**Comment by pawl** [comment]
@jnga can you also bump filters.js version to 1.0.1 here?: https://github.com/flask-admin/flask-admin/blob/e8b1b6b5aca047a4f83d685686d2632ce6206233/flask_admin/templates/bootstrap3/admin/model/list.html#L197

and here: https://github.com/flask-admin/flask-admin/blob/e8b1b6b5aca047a4f83d685686d2632ce6206233/flask_admin/templates/bootstrap2/admin/model/list.html#L197

**Comment by pawl** [comment]
@jnga Looks like this was already added in https://github.com/flask-admin/flask-admin/pull/1015

Your change removes "addFilter" and prevents the filter field from getting added at all.

You might need to install the newest version of flask-admin?: ```pip install -e git+https://github.com/flask-admin/flask-admin.git@master#egg=flask-admin```

**Comment by jnga** [comment]
@pawl Oops, I mistakenly dropped the addFilter line while trying to clean up my prior pull request #1063. I'll try the newer version, though--thanks very much.

**Pull request closed without merging**
