### PR TITLE
fix spelling spanish translation

### PR DESCRIPTION
**Pull request by roramirez**

### CODE REVIEW

**Comment by mrjoes** [comment]
Thanks for the fix, but we manage translations on crowding.com. Can you do changes there?
Spanish is here - https://crowdin.com/project/flask-admin/es-ES

**Comment by roramirez** [comment]
Hi @mrjoes, i did the update of strings on crowding.com

**Comment by pawl** [comment]
Just pushed the updated translations.

**Comment by mrjoes** [comment]
@roramirez thanks!

**Pull request closed without merging**
