### PR TITLE
Set non-POSTed fields back to default value - fixes #357

### LINKED ISSUE #357: Deleting all elements from a SelectMultipleField list does not work
I'll write a test case for this, but wanted to report it as well ...
Env: contrib.mongo

Steps:
- Add 1 or more elements to a SelectMultipleList in a model that has a db.ListField
- Save
- Delete all the elements in the list field one at a time and save
- Notice that the last element is not deleted

This is true for both string and referenced values in a list.

### PR DESCRIPTION
**Pull request by gordol**
This is especially useful when clearing out multi-select inputs.

Tested and working on MongoEngine, at least, though it should work on other currently supported ORMs as well.

See: https://github.com/flask-admin/flask-admin/issues/357

### CODE REVIEW

**Comment by gordol** [comment]
I'm not sure what the issues were in 2014, but I just tried this again, and it's working as expected.

In addition, the tests pass locally, but seem to be failing in Travis. Any ideas?

**Comment by gordol** [comment]
Here's link to the original issue, since the repo moved: https://github.com/flask-admin/flask-admin/issues/357

**Comment by gordol** [comment]
This is an issue for us again today... Would love to get this fixed upstream.

**Comment by gordol** [comment]
resolved conflict and added a little documentation in the cod: https://github.com/flask-admin/flask-admin/pull/586/commits/69b8d437d92770fcb0ddf0b64c99c5b9c2a22b7c

**Comment by gordol** [comment]
@mrjoes any chance of this being merged? would this be best to resolve by some other means?

**Comment by petrus-jvrensburg** [comment]
@gordol I want to merge this, but it's not passing the tests. 

In order to get it to work, the logic needs to be pushed down to the `update_model` method for each of the different backends, where we can handle persistence. We can't call `model.save()` from `model/base.py`.

**Comment by petrus-jvrensburg** [comment]
Closing this one now, but feel free to re-open when it's ready to merge

**Comment by gordol** [comment]
interesting, glad to see the flurry of activity here lately. I'll look at this soon...

**Pull request closed without merging**
