### PR TITLE
bootstrap fluid layout option …

### PR DESCRIPTION
**Pull request by eregnier**
Allow display flask admin using bootstrap fluid layout, depending on flask configuration FLASK_ADMIN_FLUID_LAYOUT boolean value.
I am sorry, but I dont mind where is the best place in the documentation to show this option information.

### CODE REVIEW

**Comment by eregnier** [comment]
It looks like the travis configuration is not up to date for this project ;)

**Comment by nad2000** [comment]
Hi @eregnier   , 

the build is broken. Not a biggie. need to add workaround to install correct version of Postgist, flake8 got more stringent. There are too new requirements added: E722 and E741. You might need to add following changes:

- to .travis.yml: https://github.com/flask-admin/flask-admin/pull/1556/files#diff-354f30a63fb0907d4ad57269548329e3 (to install correct version of **postgis**);
- tox.ini https://github.com/flask-admin/flask-admin/pull/1556/files#diff-b91f3d5bd63fcd17221b267e851608e8 (to ignore E722);
- flask_admin/contrib/sqla/tools.py: https://github.com/flask-admin/flask-admin/pull/1556/files#diff-70f36e099fa84f21ae730c1e207f8814 (to comply with E741 ambiguous variable name 'l');
 

That would fix the build.
Cheer!

**Comment by eregnier** [comment]
Hi nad2000, To solve this issue, I juste fetched upstream and merged to my fork. this solved the problem. Is it ok now ?

**Comment by nad2000** [comment]
yip, absolutely fine. The build was fixed a while ago merging those changes
upstream...

Radomirs Cirskis MCDBA, MCAD C#, MCSD .NET C#, ZCE PHP5, MCSD VB6 ...
M: +64 221 221 442 | E: RAD@nowITworks.eu <rad@nowitworks.eu>
[image: View my profile on LinkedIn] <http://nz.linkedin.com/in/nad2000>

**Comment by eregnier** [comment]
:up: from maintainer(s) would be appreciated. Thank you.

**Comment by eregnier** [comment]
Thank you !

**Pull request merged**
