### PR TITLE
fixes #1185

### LINKED ISSUE #1185: Flask admin peewee example failed to run with 2.8 version
I tried the Peewee integration [example](https://github.com/flask-admin/flask-admin/blob/master/examples/peewee/app.py) as plain as Copy pasting it and I am getting this error:

```
MY_ENV_PATH/bin/python "MY_PROJECT/bgadmin/app.py"
Traceback (most recent call last):
  File "MY_PROJECT/bgadmin/app.py", line 88, in <module>
    admin.add_view(UserAdmin(User))
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 170, in __init__
    menu_icon_value=menu_icon_value)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 718, in __init__
    self._refresh_cache()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 810, in _refresh_cache
    self._refresh_forms_cache()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 735, in _refresh_forms_cache
    self._create_form_class = self.get_create_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 1147, in get_create_form
    return self.get_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 1100, in get_form
    return self.scaffold_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 264, in scaffold_form
    form_class = self.scaffold_inline_form_models(form_class)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 297, in scaffold_inline_form_models
    m)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/form.py", line 213, in contribute
    for field in info.model._meta.get_fields():
AttributeError: 'ModelOptions' object has no attribute 'get_fields'
```
The version of the libraries are: Flask 0.10.1, Flask-Admin 1.4.0, peewee 2.8.0

Thanks in advance

### PR DESCRIPTION
**Pull request by gerosalesc**
Fixing compatibility with peewee 2.7.4+, tested with peewee's [example](https://github.com/flask-admin/flask-admin/blob/master/examples/peewee/app.py) As seen in this [commit](https://github.com/coleifer/peewee/commit/50c9c1dd24b7a4c48a396a9f5e88f3ea1647859a)

### CODE REVIEW

**Comment by mrjoes** [comment]
Duh, thanks for pull request.

Now we have to make decision about backwards compatibility - all versions before 2.7.4 will stop working.

**Comment by mrjoes** [comment]
OK, got response from peewee maintainer - https://github.com/coleifer/peewee/commit/50c9c1dd24b7a4c48a396a9f5e88f3ea1647859a#commitcomment-15839118

Suggested approach is:
```python
try:
    fields = model._meta.sorted_fields
except AttributeError:
    fields = model._meta.get_fields()
```

**Comment by gerosalesc** [comment]
Great, will put this into a function and add a commit to this

**Comment by gerosalesc** [comment]
@mrjoes OK it's done but the Travis is complaining about [something](https://travis-ci.org/flask-admin/flask-admin/jobs/106593731), I don't get that

**Comment by gerosalesc** [comment]
@mrjoes I closed and reopened the PR for the Travis to Retry and it succeed this time

**Pull request merged**
