### PR TITLE
Make compatible with latest peewee, fix #1117

### LINKED ISSUE #1117: Restore peewee support after incompatible changes
Flask-Admin fails to run with latest release of peewee. Moreover, extra "internal" changes are introduced 
in development version: https://github.com/coleifer/peewee/commit/50c9c1dd24b7a4c48a396a9f5e88f3ea1647859a

Here's a quick fix:
https://github.com/rudyryk/flask-admin/commit/43232f2b4df54f87bd4b507f05d492503e71db06

I'd suggest to wait for the next peewee release before adding final update to Flask-Admin.

### PR DESCRIPTION
**Pull request by rudyryk**
See issue reports:
https://github.com/flask-admin/flask-admin/issues/1117
https://github.com/coleifer/peewee/issues/765

### CODE REVIEW

**Comment by tmecha** [comment]
This worked for me. Thank you please commit.
-Todd

**Comment by datboitom** [comment]
I tried to put this fix in running Python 2.7 and I encounter the following error:

AttributeError: 'ModelOptions' object has no attribute 'sorted_field_names'

The same error shown in the fail CI builds, it's not entirely obvious to me at first glance why that's happening.

**Comment by rudyryk** [comment]
@datboitom This is working only on current development branch at the moment, e.g. you should clone both peewee and flask-admin and install them via `python setup.py develop`.

**Comment by pawl** [comment]
Closing in favor of #1125

**Pull request closed without merging**
