### PR TITLE
Correctly process sqlalchemy_utils ChoiceType fields

### PR DESCRIPTION
**Pull request by bakatrouble**
Fixing issue with `ChoiceType` field described in https://github.com/flask-admin/flask-admin/issues/1134#issuecomment-317290816

### CODE REVIEW

**Comment by nad2000** [comment]
Hi @bakatrouble    , 

the build is broken. Not a biggie. need to add workaround to install correct version of Postgist, flake8 got more stringent. There are too new requirements added: E722 and E741. You might need to add following changes:

- to .travis.yml: https://github.com/flask-admin/flask-admin/pull/1556/files#diff-354f30a63fb0907d4ad57269548329e3 (to install correct version of **postgis**);
- tox.ini https://github.com/flask-admin/flask-admin/pull/1556/files#diff-b91f3d5bd63fcd17221b267e851608e8 (to ignore E722);
- flask_admin/contrib/sqla/tools.py: https://github.com/flask-admin/flask-admin/pull/1556/files#diff-70f36e099fa84f21ae730c1e207f8814 (to comply with E741 ambiguous variable name 'l');
 

That would fix the build.
Cheer!

**Comment by bakatrouble** [comment]
Looks fine now

**Comment by andrewmwilson** [comment]
Is this likely to get merged? It would be very useful!

**Comment by scythargon** [comment]
+1

**Comment by joshua-s** [comment]
Bump

**Comment by bakatrouble** [comment]
Fixed conflicts

**Comment by mrjoes** [comment]
I'm sorry, but I can't accept this pull request.

SQLAlchemy is just one of the supported ORM backends. The change in question changes the core `Select2Field` implementation that has nothing to do with databases. 

If you want to support `Choice` type - I would recommend subclassing it and putting it in `contrib.sqla.fields`. Then you can either override the form scaffolding logic (use custom field instead of generic Select2Field) or just explicitly use it by overriding the form settings in the view class.

**Pull request closed without merging**
