### PR TITLE
add `name` argument to `expose` decorator …

### PR DESCRIPTION
**Pull request by LotosikRa**
…and make it enabled inside `AdminViewMeta`

### CODE REVIEW

**Comment by LotosikRa** [comment]
Ok, PR isn't ready. I will fix it soon.

**Comment by LotosikRa** [comment]
Now it seems to be ready

**Comment by LotosikRa** [comment]
Fork with this changes is working good. Can you merge it?

**Comment by petrus-jvrensburg** [comment]
@LotosikRa Is this PR still relevant? 

I'm not completely sure I understand the use-case, so I'm closing this. But please re-open if there's something I'm missing.

**Pull request closed without merging**
