### PR TITLE
Enable Peewee tests on Python 3

### PR DESCRIPTION
**Pull request by cjmayo**
Working for me locally, but I don't have Python 2 so let's see how that goes.

Requested in https://github.com/flask-admin/flask-admin/issues/1721.

### CODE REVIEW

**Comment by cjmayo** [comment]
It passes on Python 2.7, but fails on Python 3.4. I was going to submit another PR to drop Python 3.4 testing - it is now EOL - would that be an acceptable solution for this?

**Comment by cjmayo** [comment]
Rebased on current master without any changes to pass checks.

**Comment by ulgens** [comment]
@mrjoes I think this PR should be merged now but I don't have permissions to rebase it.

**Comment by cjmayo** [comment]
I've rebased on master - without testing myself. Needs a further updated.

**Comment by cjmayo** [comment]
Some of the rebase had to be done manually and I only converted part of this:
```diff
-    eq_(req.data, u'[[%s, "foo"]]' % model2.id)
+    eq_(req.data, b'[[%d, "foo"]]' % model2.id)
```
I did the u' -> b' but not %s -> %d.

Fixed that.

Failures are elsewhere now:

```
=========================== short test summary info ============================
FAILED flask_admin/tests/mongoengine/test_basic.py::test_nested_list_subdocument
FAILED flask_admin/tests/mongoengine/test_basic.py::test_nested_sortedlist_subdocument
FAILED flask_admin/tests/mongoengine/test_basic.py::test_sortedlist_subdocument_validation
FAILED flask_admin/tests/mongoengine/test_basic.py::test_list_subdocument_validation
FAILED flask_admin/tests/sqla/test_form_rules.py::test_rule_inlinefieldlist
FAILED flask_admin/tests/sqla/test_form_rules.py::test_inline_model_rules - a...
FAILED flask_admin/tests/sqla/test_inlineform.py::test_inline_form - assert 5...
FAILED flask_admin/tests/sqla/test_inlineform.py::test_inline_form_required
FAILED flask_admin/tests/sqla/test_inlineform.py::test_inline_form_ajax_fk - ...
FAILED flask_admin/tests/sqla/test_inlineform.py::test_inline_form_self - Typ...
FAILED flask_admin/tests/sqla/test_inlineform.py::test_inline_form_base_class
FAILED flask_admin/tests/sqla/test_postgres.py::test_hstore - assert 500 == 302
===== 12 failed, 130 passed, 2 skipped, 5 xfailed, 146 warnings in 38.45s ======
```

**Comment by ulgens** [comment]
@cjmayo Can you please trigger this again?

**Comment by cjmayo** [comment]
Rebased on master. All passed now.

**Pull request merged**
