### PR TITLE
Adding support for Bootswatch.com themes for b2 and b3

### PR DESCRIPTION
**Pull request by rochacbruno**
Optionally if defined

``` python
app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'
```

available swatchs in http://bootswatch.com

License of swatches is MIT (the same as bootstrap)
- Core flask admin got static/swatch folder with all the swatch files
- Changed base.html to use the defined swatch, if not defined it uses swatch/default which is pure bootstrap.min
- Examples swatch and swatch3 created

@mrjoes @pawl if you think it is not nice to include all swatch files, maybe we can create a plugin system to be installed. `pip install flask-admin-swatch` and a form of the plugin to override the base.html block.

cerulean
cerulean

cosmo
cosmo

united
united

slate
slate

More 10 themes

### CODE REVIEW

**Comment by pawl** [comment]
Couldn't this be distilled down to a layout.html example with this?:
```
{% extends 'admin/base.html' %}

{% block head_tail %}
  {{ super() }}
    {% set bootswatch_theme = 'cyborg' %}
    {% set bootswatch_version = '3.0.0' %}
    <link href="//netdna.bootstrapcdn.com/bootswatch/{{ bootswatch_version }}/{{ bootswatch_theme }}/bootstrap.min.css" rel="stylesheet" >
{% endblock %}
```

And this when the admin object is declared:
```admin = admin.Admin(app, 'Example: Bootswatch', base_template='layout.html', template_mode='bootstrap3')```


If someone is changing the styling of flask-admin, they're likely going to be overriding base.html anyway.

**Comment by rochacbruno** [comment]
:+1: @pawl  I will convert in to a layout example

**Comment by harishkashyap** [comment]
@rochacbruno Thanks a ton! please watch out for my email :)

**Comment by m3talstorm** [comment]
Would be super dupa awesome if this could be merged in :)

**Pull request merged**
