### PR TITLE
Support import data via csv or xls

### PR DESCRIPTION
**Pull request by caffeinatedMike**
This closes #2044 as it picks up where that PR left off.

cc: @mrjoes @michaelbukachi @Insutanto @DaniilAnichin please feel free to offer feedback

### CODE REVIEW

**Comment by caffeinatedMike** [comment]
@michaelbukachi Can you check my work here, please? Everything seems to be in order now.

@mrjoes For some reason the following 2 tests are failing, any idea why when I haven't touched the related components?
```
flask_admin/tests/test_model.py::test_safe_redirect
flask_admin/tests/test_model.py::test_mockview
```

**Comment by ibushong** [comment]
#2269 should (hopefully) address those test failures

**Comment by michaelbukachi** [comment]
@ibushong so should we prioritize that first?

**Comment by ibushong** [comment]
@michaelbukachi I think that's prob a good idea.

**Comment by Dhruv-Sachdev1313** [comment]
Hey @caffeinatedMike : I tried using your forked repo to have the import functionality. Even though it say `Records added successfully` but doesn't really add any rows. 

On further debugging, we find in this code by printing imported data, it gives an empty list!, so the code never enters the loop and directly returned True
```
 model_columns = {
            header: reversed_labels[header]
            if header in reversed_labels
            else dbify_name(header)
            for header in imported_data.headers
        }
        print("imported data is")
        print(type(imported_data))
        print(imported_data.export('json'))
        for row in imported_data:
            print(row)
            try:
                model = self.model(**{
                    model_columns[key]: row[i]
                    if model_columns[key] not in self.column_formatters_import
                    else self.column_formatters_import[model_columns[key]](self, row[i])
                    for i, key in enumerate(imported_data.headers)
                })
                self.session.add(model)
                self.session.commit()
```

**Pull request closed without merging**
