### PR TITLE
updates to 'create' & 'edit' view buttons 

### PR DESCRIPTION
**Pull request by petrus-jvrensburg**
This builds on @pawl's PR #991.

I put back the cancel button, and right-aligned it. While keeping the rest of the buttons left-aligned.

### CODE REVIEW

**Comment by petrus-jvrensburg** [comment]
This is what it looks like for the **create** view:

screen shot 2015-08-15 at 3 08 11 pm

And here's the **edit** view:

screen shot 2015-08-15 at 3 08 28 pm

**Comment by pawl** [comment]
This makes the buttons in the modal appear a bit odd: 

I can't think of a better solution, so I went looking for some inspiration (pictures below).

Some observations:
* The examples with all three save buttons usually don't have a cancel button. The cakephp example is the only exception, it includes all 4 buttons.
* A lot of the examples only have a save button (and sometimes a cancel button). I like the simplicity. The additional save buttons are a "power user" feature. Since our target audience is admins, they'll probably appreciate the extra buttons more than the simplicity.

Django Suit: Django Suit
Django Grappelli: Django Grappelli
ActiveAdmin (ruby on rails): ActiveAdmin
Keystone JS: 
Light Admin (java): 
Fiends of Cake CRUD v4 (php): 
Yii 2.0 (php): 
Crud admin generator (php): 
Play framework (java): 
ASP.net example: 
Grails: Grails
Google Calendar: 
Wordpress:

**Comment by mrjoes** [comment]
Lets stick all buttons together, as cancel button really stands out?

**Comment by pawl** [comment]
@mrjoes Done. See #995

**Pull request closed without merging**
