### PR TITLE
Sqlalchemy utils types

### LINKED ISSUE #1134: Flask-admin doesn't know what to do with sqlalchemy_utils.EmailType columns
My project defines a [`sqlalchemy_utils.EmailType`](https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/types/email.py) column and while it's listed as a column in the list view, it's not displayed as an editable field in the form view.

To fix this, I had to manually override `scaffold_form()` to include the field as a `TextField`, similar to the snippet in http://stackoverflow.com/a/13551851.

This took me a while to debug and work around, so I'm documenting it here in case anyone else runs into it.

I'm not really sure what an appropriate "fix" for this might be, if any exists, as I'm very new to flask-admin and not even very familiar with sqlalchemy-utils or WTForms. I guess it'd be nice if there were some logging output from flask-admin that might help developers understand why fields might not be showing up, and documentation on ways to work around it?

### PR DESCRIPTION
**Pull request by petrus-jvrensburg**
This adds support for several SQLAlchemy-Utils data types and demonstrates this in `examples/sqla/app.py`. It also makes it possible for choice-type fields to be editable from the list view.

For more, see https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html. Support for these ones are implemented in this PR:

* ArrowType
* ChoiceType
* ColorType
* CurrencyType
* Email
* IPAddressType
* TimezoneType
* URLType
* UUIDType

Fixes #1134, #1372, #1465, #1306

### CODE REVIEW

**Comment by SBillion** [comment]
Nice :+1:

**Comment by joshua-s** [comment]
Can this be merged please :)

**Comment by joshua-s** [comment]
Can this be merged please @mrjoes

**Comment by petrus-jvrensburg** [comment]
Just fixed a merge-conflict. Anyone willing to review?

**Comment by petrus-jvrensburg** [comment]
@mrjoes Any objections to merging this one?

**Comment by mrjoes** [comment]
Nope, it is looking good. I was hesitating to accept a similar MR a few years back because sqlalchemy_utils is mixing presentational logic with the DB schemas, but I also understand why it is fairly helpful to have this in the core instead of a third-party plugin.

**Pull request merged**
