### PR TITLE
remove identity_token from fields.py

### PR DESCRIPTION
**Pull request by dmelo**
On the method `get_pk_from_identity`, replace the `identity_token` method by `__mapper__.primary_key_from_instance`, that returns only the primary_key, in an attempt to solve issue #1583

### CODE REVIEW

**Comment by andreoliwa** [comment]
Looking at the [failed builds](https://travis-ci.org/flask-admin/flask-admin/builds/322881886?utm_source=github_status&utm_medium=notification), it seems that SQLAlchemy 1.2 has dropped support for Python 2.6.

```
Collecting SQLAlchemy>=0.8.0 (from Flask-SQLAlchemy>=0.15->-r /home/travis/build/flask-admin/flask-admin/requirements-dev.txt (line 2))
  Downloading SQLAlchemy-1.2.0.tar.gz (5.5MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mXZzQi/SQLAlchemy/setup.py", line 16, in <module>
        raise Exception("SQLAlchemy requires Python 2.7 or higher.")
    Exception: SQLAlchemy requires Python 2.7 or higher.
```

Maybe if you change `tox.ini` and remove Python 2.6 as well, the build could pass.

```
envlist =
py{27,33,34,35,36}-WTForms{1,2}
```

But then Flask-Admin won't support Python 2.6 by extension. 🤔

**Comment by jaysonsantos** [comment]
As SQLAlchemy is a fundamental part of flask-admin maybe it is better to drop 2.6 here too.

**Comment by andreoliwa** [comment]
Broken build due to timeout: https://travis-ci.org/flask-admin/flask-admin/jobs/325321900
I think restarting your build should work. 

Also, there is another pull request trying to fix this same problem: #1586

**Comment by dmelo** [comment]
#1586 should solve the problem as well. I will try and test it this weekend.

**Comment by andreoliwa** [comment]
#1586 is already merged (even though it fails with Python 2.6).
This pull request might be obsolete now.

**Comment by dmelo** [comment]
@andreoliwa I agree. Closing the PR.

**Pull request closed without merging**
