### PR TITLE
Fix several messages in russian translation

### PR DESCRIPTION
**Pull request by Ty3uK**

### CODE REVIEW

**Comment by pawl** [comment]
@Ty3uK please add these translations through this site: https://crowdin.com/project/flask-admin/ru

Can you also add a translation for "export" too?

**Comment by Ty3uK** [comment]
OK

**Comment by Ty3uK** [comment]
Done, please check.

**Comment by pawl** [comment]
@Ty3uK thank you! I just pushed your improvements in this commit: d931105abb162ad1d57b4c2457a2353488bd34c5

**Comment by Ty3uK** [comment]
@pawl, yep, thanks :-)

**Pull request closed without merging**
