### PR TITLE
add json support to SQLA backend

### PR DESCRIPTION
**Pull request by pawl**
This pull request adds the ability to edit JSON columns to the SQLA backend.

It accomplishes this by moving the GeoAlchemy backend's JSONField into `flask_admin/form/fields.py` to be shared between the two backends. Also, some improvements were made to the JSONField's ability to handle non-ascii characters.

Editing:
screenshot1

List View:
screenshot2

Invalid JSON:
screenshot3

### CODE REVIEW

**Comment by mrjoes** [comment]
Lets use PostgreSQL 9.4. Otherwise - good to go.

**Comment by pawl** [comment]
Just changed it to use 9.4 here: https://github.com/flask-admin/flask-admin/pull/1245/commits/711b33e4de810cc39ef90576970e5c5b84a01e29

**Comment by pawl** [comment]
@mrjoes I just updated translations. Think we're ready for a release that includes this?

**Comment by mrjoes** [comment]
I think so. Do we have anything else pending?

**Pull request merged**
