### PR TITLE
Fix in translations

### PR DESCRIPTION
**Pull request by PaulWasTaken**
https://github.com/flask-admin/flask-admin/issues/1532

### CODE REVIEW

**Comment by nad2000** [comment]
Hi @PaulWasTaken    , 

the build is broken. Not a biggie. need to add workaround to install correct version of Postgist, flake8 got more stringent. There are too new requirements added: E722 and E741. You might need to add following changes:

- to .travis.yml: https://github.com/flask-admin/flask-admin/pull/1556/files#diff-354f30a63fb0907d4ad57269548329e3 (to install correct version of **postgis**);
- tox.ini https://github.com/flask-admin/flask-admin/pull/1556/files#diff-b91f3d5bd63fcd17221b267e851608e8 (to ignore E722);
- flask_admin/contrib/sqla/tools.py: https://github.com/flask-admin/flask-admin/pull/1556/files#diff-70f36e099fa84f21ae730c1e207f8814 (to comply with E741 ambiguous variable name 'l');
 

That would fix the build.
Cheer!

**Comment by PaulWasTaken** [comment]
Greetings,
I am new to git, could you explain what exactly do you want me to do? Rebase, cherry-pick or merge this commits? What would be the best way to do it?

**Comment by nad2000** [comment]
Hi Paul,

the best way would be the simplest way. Just add thous few changes manually
:)
Cheer!

Radomirs Cirskis MCDBA, MCAD C#, MCSD .NET C#, ZCE PHP5, MCSD VB6 ...
M: +64 221 221 442 | E: RAD@nowITworks.eu <rad@nowitworks.eu>
[image: View my profile on LinkedIn] <http://nz.linkedin.com/in/nad2000>

**Comment by PaulWasTaken** [comment]
I have done what you asked but there is still one error

**Pull request merged**
