### PR TITLE
Allow to use inline models in One To One relationships

### PR DESCRIPTION
**Pull request by symstu**

### CODE REVIEW

**Comment by crazy2k** [comment]
What can we do to get this PR more attention? Seems like a really basic thing that's not supported.

**Comment by caffeinatedMike** [comment]
@symstu Can you please add a test for this new Inline model to make sure it has no unintended consequences on the rest of the tests?

**Comment by symstu** [comment]
> @symstu Can you please add a test for this new Inline model to make sure it has no unintended consequences on the rest of the tests/codebase?

ok

**Comment by abstractOwl** [comment]
Hi @symstu, do you have time to add unit tests for this feature? Really looking forward to finally getting this feature added to Flask-Admin

**Review by caffeinatedMike — APPROVED** [review]
@mrjoes Approved. This can be merged.

**Comment by caffeinatedMike** [comment]
@symstu I've been digging into this feature and I've run into two problems so far.

1. For me, I had to swap the `mapper` and `target_mapper` variables because my relationships kept showing up as ONETOMANY.
    ```python
    # _calculate_mapping_key_pair function in sqla form.py
    # mapper = model._sa_class_manager.mapper
    # target_mapper = info.model._sa_class_manager.mapper.base_mapper
    mapper = info.model._sa_class_manager.mapper.base_mapper
    target_mapper = model._sa_class_manager.mapper
    ```
2. For some reason when `inline_converter = InlineOneToOneModelConverter` is set in an `InlineForm` the `form_rules` defined within that class are not used and the form renders as a single field that looks up the instance of the model.
    ```python
    class GoogleStorageInlineForm(InlineFormAdmin):
        inline_converter = InlineOneToOneModelConverter
        form_columns = ("use_gs", "bucket_name", "folder_path")
        form_rules = (
            rules.Container(
                "custom_macros.render_accordion_tab",
                rules.FieldSet(rules=(
                    rules.Field("use_gs", render_field="custom_macros.render_checkbox"),
                    rules.Row("bucket_name", "folder_path")
                )), header="Google Storage"
            ),
        )
    ```

With `inline_converter = InlineOneToOneModelConverter`
image
Without
image

**Pull request merged**
