### PR TITLE
Add modals to FileAdmin, minor changes to forms

### PR DESCRIPTION
**Pull request by pawl**
This pull request mainly adds modals to Fileadmin's edit, mkdir, upload, and rename views.

Minor changes:
* Add header to create directory and file upload forms.
* Add success messages when directory is created or file is uploaded.
* Added get_text to untranslated "This file cannot be edited for now." message.
* Simplifed edit_view and create_view modal button macro call by removing unnecessary parameters.
* Changed "Please provide new name for" in rename view header to simply "Rename".
* Changed "You are editing" in edit view header to simply "Editing".
* Add tabs to .edit_view for in model_view to be consistent with create view.
* Add missing "{% block actions %}" block to bootstrap3/admin/model/list.html (bootstrap2 has it).
* Changed "modal_header" block in edit_view and create_view name to "header_text" to indicate it's not just for modals.
* Now using simpler "if modal" in templates instead of "if request.args.get('modal')".

### CODE REVIEW

**Comment by pawl** [comment]
Here are some screenshots.

Bootstrap 3 Rename File: Bootstrap 3 Rename File
Bootstrap 3 Editing File Contents: Bootstrap 3 Editing File Contents
Bootstrap 3 Create Directory: Bootstrap 3 Create Directory
Bootstrap 3 Upload File: Bootstrap 3 Upload File
Tabs on edit_view when modal is disabled: edit_view tabs

**Comment by pawl** [comment]
@petrus-jvrensburg and @mrjoes 

Any objections to merging this?

**Comment by mrjoes** [comment]
No objections from me.

**Comment by petrus-jvrensburg** [comment]
I'm happy

**Pull request merged**
