### PR TITLE
Add BaseModelView.table_prefix_html for insert some HTML above list t…

### PR DESCRIPTION
**Pull request by pedia**
Demo:
flask-admin table prefix demo

It's a bit useful to the end-user of website.

Hope help.

### CODE REVIEW

**Comment by ufo911** [comment]
Small Good PR

**Comment by pedia** [comment]
Be caught ;)
Fix bootstrap2 done

**Comment by pedia** [comment]
After pushed a new head(nothing changed),  travis is running flake8 again.
I think it will be passed.

**Comment by pedia** [comment]
@ufo911 The test passed, maybe ci is not stable enough.

**Comment by pedia** [comment]
@ufo911 How about merge this one?

**Comment by ufo911** [comment]
@pedia
Sorry I am not maintainer

**Comment by pedia** [comment]
@mrjoes 
How about this PR?

**Comment by petrus-jvrensburg** [comment]
I'm not sure this is all that useful. For adding your own content to the builtin views, rather take this approach: https://flask-admin.readthedocs.io/en/latest/introduction/#working-with-the-built-in-templates

I updated the 'sqla' example app, so that you can see this in action.

**Pull request closed without merging**
