### PR TITLE
Docs refactor

### LINKED ISSUE #903: Docs refactor
The documentation is great, but for a completely new user, there's a lot to read through before they have a good overview of what's possible. To make it more obvious for a user to see how to do all of the common things, I want to refactor the docs into the following sections:

Getting started
-------------------
+ Initialization
+ Adding model views
+ Overriding the index page

Auth & permissions
-------------------
+ Basic auth
+ Flask-Security

Customizing the builtin model views
-------------------
+ Image fields
+ HTML fields
+ List view options
+ Form view options

Adding your own views
-------------------
+ Standalone views
+ Overriding specific model views

Advanced
-------------------
+ Enabling localization
+ Handling foreign key relations inline
+ Many-to-many relations
+ Managing files & folders
+ Managing geographical models
+ Customizing builtin forms via form rendering rules
+ Using different model backends
+ Rolling your own authentication
+ Usage tips
+ Adding a Redis console

API 
-------------------
+ (auto generated from code)

### PR DESCRIPTION
**Pull request by petrus-jvrensburg**
Closes #903. 

This re-organises the documentation as per the sections below. The content was refactored to eliminate duplication, and to ensure consistent language throughout the docs. 

The 'introduction' page aims to surface everything a new user would need to know, while the 'advanced' page pulls together the rest of the content. These changes should make it easier for users to find and learn about the existing features.

Introduction to Flask-Admin
-----------------------------------------
+ Getting Started
+ Authorisation & Permissions
+ Customising Builtin Views
+ Adding Your Own Views
+ Working with the builtin templates

Advanced Functionality
------------------------------------
+ Localization With Flask-Babelex
+ Managing Files & Folders
+ Adding a Redis Console
+ Replacing Individual Form Fields
+ Managing Geographical Models
+ Customising Builtin Forms via Rendering Rules
+ Using Different Database Backends
+ Migrating From Django
+ Overriding the Form Scaffolding

Adding a Model Backend
------------------------------------
+ Extending BaseModelView
+ Implementing filters

API
-------
(autogenerated)

### CODE REVIEW

**Comment by mrjoes** [comment]
I will go over this today.

**Comment by plaes** [comment]
One nitpick - lots of section/subsection titles are wrongly formatted.
Instead of this:
```
Title
------
```
or this:
```
Title
---
```

Should be:
```
Title
-----
```

**Comment by petrus-jvrensburg** [comment]
@mrjoes Any thoughts so far? Are you happy with the overall structure?

**Comment by mrjoes** [comment]
Yep, went through it. New structure is better for sure.

We also need section for Flask extension developers showing how easy it is to distribute Flask-Admin components with their extension.

**Comment by petrus-jvrensburg** [comment]
Okay great. If you can write down the basics, then I'd be happy to flesh it out in the docs. 

Meanwhile, are you still reviewing this PR, or can we merge?

**Comment by mrjoes** [comment]
Didn't check if it would compile (as @plaes mentioned, headers are not properly lined up), but if it does - good to go.

**Pull request merged**
