### PR TITLE
Add 'data-no-autoclose' attribute to select2 widget

### PR DESCRIPTION
**Pull request by sebleblanc**
By setting the 'data-no-autoclose' attribute on the Select2Widget
object, the Select2 JavaScript widget will not automatically close
itself after an object has been selected.

You can use it this way:
    class MyModelView(ModelView):
        form_widget_args = dict(
            field = {'data-no-autoclose': u'1'} # any value will also do
            )

IMO the `u'1'` part is counter-intuitive (setting it to any value has the same behaviour) but I am respecting the pattern used by other attributes of the widget (e.g. 'data-allow-blank').

This commit references issue #920. I based it off v1.1.0 simply because my project uses this version and I could not test it with the latest. It should be easy to merge though.

### CODE REVIEW

**Comment by pawl** [comment]
The new select2 4.0 allows setting options through data attributes. It might just be better to upgrade select2 instead of adding more hacks.

**Comment by sebleblanc** [comment]
In the meantime this fix works for me.

**Comment by pawl** [comment]
Unfortunately, the bootstrap theme for Select2 4.0 is still a work in progress: https://github.com/select2/select2-bootstrap-theme

I tried testing 4.0 without the bootstrap theme for a few minutes and noticed a few problems:
* Select2 input fields not the same size as normal input fields: https://i.imgur.com/BAKdbTF.png
* More size issues: https://i.imgur.com/LG2h0JW.png
* X button here doesn't work: https://i.imgur.com/l5V0WOH.png

**Comment by petrus-jvrensburg** [comment]
Closing this. But please re-open if it's still an issue.

**Pull request closed without merging**
