### PR TITLE
support bootstrap 4 and bootswatch themes.

### PR DESCRIPTION
**Pull request by momentxu**
I find the branch of bootstrap4 is no longer develop, but I need the new style of bootswatch.
So, I created the bootstrap4 template mode for flask-admin and support bootswatch.
It is similar to the bootstrap3 template. Yes, I transformed bootstrap3 template to bootstrap4 template. 😸 
I am open to any suggestions to improve my codes and make it available to all. 😺

### CODE REVIEW

**Comment by momentxu** [comment]
So sad, I have done the same thing...
Duplicate of #1847 #1674 #1845 
But, this request support  bootswatch.

**Comment by nurockplayer** [comment]
How about this PR?
@petrus-jvrensburg

**Comment by momentxu** [comment]
> How about this PR?
> @petrus-jvrensburg

I didn't find flask-admin in his repositories, maybe he has not willing to finish it. 😸

**Comment by momentxu** [comment]
@mrjoes Maybe we should finish it. Supporting bootstrap4 is meaningful. 😸

**Comment by rsnyman** [comment]
I'm using @momentxu 's branch, but I'd much prefer to use main flask-admin. Is someone looking into this?

**Comment by petrus-jvrensburg** [comment]
Yes, let me check this out 👍

**Comment by petrus-jvrensburg** [comment]
I would have loved to merge, but this still needs work.  I tried it out locally, but:

• I'm seeing a bunch of 404's in the console, relating to CSS & JS static files.
• Modals aren't working (set `create_modal = True` or  `edit_modal = True` and you'll see `TypeError: undefined is not an object (evaluating 'Util.getSelectorFromElement')` when trying to create / edit.
• Inline-editing is broken (set `column_editable_list=[...]` and you'll see `TypeError: undefined is not an object (evaluating 'Util.getSelectorFromElement')` when trying to edit something from the list view.

**Comment by petrus-jvrensburg** [comment]
I merged this into the `bootstrap4` branch, which includes a fix that makes the modal windows show. @momentxu can you help fixing some of the items mentioned above, on that branch?

**Comment by Insutanto** [comment]
> I merged this into the `bootstrap4` branch, which includes a fix that makes the modal windows show. @momentxu can you help fixing some of the items mentioned above, on that branch?

Yes, I am glad to work on it!

**Pull request closed without merging**
